### PR TITLE
Add support for thunks with extraArguments

### PR DESCRIPTION
**Pull request by PhilSwanson**
**What**
This PR implements support for thunks with extra arguments, as permitted by redux-thunk. 
 https://github.com/reduxjs/redux-thunk#injecting-a-custom-argument.  Unfortunately, this constitutes a breaking change and this will require a major version bump.

**Why is this a breaking change:**
This is a breaking type change because we need an additional generic parameter in the call of `createAsyncAction<ActionType, ExtraArguments>(...)` to represent the type of the extra arguments.

~~Our current version of flow in async-action is `0.97`, and this would not be a breaking change if we were on `0.101.0` because we could use a default existential type to represent the ExtraArguments.  Sadly we live in the present and not the future.~~

~~Introduction of default function generics:~~
~~> Function type parameters may now use default arguments. This is not yet supported by babel.
 https://github.com/facebook/flow/releases/tag/v0.101.0~~

It's now the future and we've just upgraded flow to 0.105.2 as part of this PR.

### CODE REVIEW

**Comment by sterlingwes** [comment]
Neat  didn't realize this was a thing

Curious what's the use case for you? A reference to the API instance is an interesting use case

Probably should specify `redux-thunk` as a peer dep now that we have a floor this requires (`>=2.1.0`)?

**Comment by sterlingwes** [comment]
FYI [the existential type is deprecated](https://flow.org/en/docs/linting/rule-reference/#toc-deprecated-type) :smile-cry:

> ... as this type is unsafe and usually just equivalent to any. The effect of * can generally be achieved by simply not providing a type annotation.

**Comment by PhilSwanson** [comment]
> Curious what's the use case for you? A reference to the API instance is an interesting use case

I guess there's two parts of this for me:
1.  Given that this repo is now public, we should probably support this component of the redux-thunk API
2. I would like to expose `getConfig` from terminal as an extraArgument to support the testability of our actions and no longer needing to jest.mock() it everywhere.

**Comment by sterlingwes** [comment]
🎉  That'd be nice

**Pull request merged**
